version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /home/dot:/home/dot
      - /home/dot/work/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/dot/work/docker/nginx/favicon.ico:/usr/share/nginx/html/favicon.ico
      - /home/dot/work/docker/php/dokuwiki:/usr/share/nginx/html/dokuwiki
      - /home/dot/work/docker/cgi/dc:/usr/share/nginx/html/dc
    depends_on:
      - php
      - cgi
    restart: always
  php:
    image: php:7-fpm
    volumes:
      - /home/dot/work/docker/php/dokuwiki:/usr/share/nginx/html/dokuwiki
    restart: always
  cgi:
    build: cgi
    volumes:
      - /home/dot/work/docker/cgi/dc:/usr/share/nginx/html/dc
    restart: always
